/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.wifiaware;

import android.annotation.SuppressLint;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.net.wifi.aware.AttachCallback;
import android.net.wifi.aware.DiscoverySessionCallback;
import android.net.wifi.aware.PeerHandle;
import android.net.wifi.aware.PublishConfig;
import android.net.wifi.aware.PublishDiscoverySession;
import android.net.wifi.aware.SubscribeConfig;
import android.net.wifi.aware.SubscribeDiscoverySession;
import android.net.wifi.aware.WifiAwareManager;
import android.net.wifi.aware.WifiAwareSession;
import android.os.Build;

import androidx.annotation.RequiresApi;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import java.nio.charset.StandardCharsets;
import java.util.List;


@RequiresApi(api = Build.VERSION_CODES.O)
@SuppressLint("MissingPermission")
@Kroll.module(name = "TiWifiaware", id = "ti.wifiaware")
public class TiWifiawareModule extends KrollModule {

    // Standard Debugging variables
    private static final String LCAT = "TiWifiawareModule";
    private static final boolean DBG = TiConfig.LOGD;
    WifiAwareManager wifiAwareManager;
    WifiAwareSession awareSession;
    SubscribeDiscoverySession discoverySession;
    PeerHandle sessionPeer;

    public TiWifiawareModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }

    @Kroll.getProperty
    public boolean hasFeature() {
        return TiApplication.getAppRootOrCurrentActivity().getPackageManager().hasSystemFeature(PackageManager.FEATURE_WIFI_AWARE);
    }

    @Kroll.method
    public void isAvailable() {
        Context context = TiApplication.getAppRootOrCurrentActivity();
        wifiAwareManager = (WifiAwareManager) context.getSystemService(Context.WIFI_AWARE_SERVICE);
        IntentFilter filter = new IntentFilter(WifiAwareManager.ACTION_WIFI_AWARE_STATE_CHANGED);
        BroadcastReceiver myReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                KrollDict kd = new KrollDict();
                if (wifiAwareManager.isAvailable()) {
                    kd.put("available", true);
                } else {
                    kd.put("available", false);
                }
                fireEvent("available", kd);
            }
        };
        context.registerReceiver(myReceiver, filter);
    }

    @Kroll.method
    public void subscribe(String serviceName) {
        SubscribeConfig config = new SubscribeConfig.Builder().setServiceName(serviceName).build();
        if (awareSession != null) {
            awareSession.subscribe(config, new DiscoverySessionCallback() {
                @Override
                public void onSubscribeStarted(SubscribeDiscoverySession session) {
                    discoverySession = session;
                    fireEvent("subscribed", new KrollDict());
                }

                @Override
                public void onServiceDiscovered(PeerHandle peerHandle, byte[] serviceSpecificInfo, List<byte[]> matchFilter) {
                    fireEvent("discovered", new KrollDict());
                    sessionPeer = peerHandle;
                }
            }, null);
        }
    }

    @Kroll.method
    public void send(String text) {
        if (discoverySession != null && sessionPeer != null) {
            discoverySession.sendMessage(sessionPeer, 0, text.getBytes(StandardCharsets.UTF_8));
        }
    }


    @Kroll.method
    public void publish(String serviceName) {
        wifiAwareManager.attach(new AttachCallback() {
            @Override
            public void onAttached(WifiAwareSession session) {
                // Once attached, we can publish or subscribe
                PublishConfig publishConfig = new PublishConfig.Builder().setServiceName(serviceName).build();
                awareSession = session;
                session.publish(publishConfig, new DiscoverySessionCallback() {
                    @Override
                    public void onPublishStarted(PublishDiscoverySession pubSession) {
                        fireEvent("published", new KrollDict());
                    }

                    @Override
                    public void onMessageReceived(PeerHandle peerHandle, byte[] message) {
                        super.onMessageReceived(peerHandle, message);
                        KrollDict kd = new KrollDict();
                        String msgStr = new String(message, java.nio.charset.StandardCharsets.UTF_8);
                        kd.put("text", msgStr);
                        fireEvent("message", kd);
                    }
                }, null);
            }

            @Override
            public void onAttachFailed() {
                Log.e(LCAT, "Failed to attach to Wi-Fi Aware session.");
            }
        }, null);
    }

}

